### ISSUE TITLE
Add support for running vue

### ISSUE THREAD

**Issue by Attacler** [directus-community/extension-toolkit#4]
Basicly if you want to use Vuejs to create a interface or something, the index.js (inside /src) should contain:
`import Vue from 'vue';
new Vue({
	render: h => h(InterfaceComponent)
}).$mount('#app');
`
This will allow you do use the VUEJS live reloading (outside directus).

**Comment by Jonesus** [comment]
Reference to previous discussion in Directus Discord: https://discord.com/channels/725371605378924594/835244612356145167/840290666747265095

So your proposal would be to allow for the extension to be ran outside of Directus in a standalone web server (with for example `vue-cli-service serve`) ? I haven't really tried developing any Vue extensions so not sure how useful this would be, as I figure for proper testing you'd almost always need at least some data from Directus's side?

Doesn't seem like too big of a change though, so I guess it could be a separate option when initializing a new extension with the toolkit, I'm not entirely convinced it should be included by default in all extensions

**Comment by Attacler** [comment]
Please dont add this and just add --watch in the package.json (npm run build)
basicly you can set it up to work with watch mode so you only have to do f5 to see it show up
